# Generated by Django 4.2.6 on 2024-04-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0004_remove_tender_results_tenderresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='created_at',
            field=models.DateField(),
        ),
    ]
