# Generated by Django 4.2.6 on 2024-04-17 11:40

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0005_alter_tender_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tenderresult',
            name='result_description',
        ),
        migrations.AddField(
            model_name='tender',
            name='en_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='en Description'),
        ),
        migrations.AddField(
            model_name='tender',
            name='en_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='kg_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='kg Description'),
        ),
        migrations.AddField(
            model_name='tender',
            name='kg_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='ru_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='ru Description'),
        ),
        migrations.AddField(
            model_name='tender',
            name='ru_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tenderresult',
            name='en_result_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='en Results'),
        ),
        migrations.AddField(
            model_name='tenderresult',
            name='kg_result_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='kg Results'),
        ),
        migrations.AddField(
            model_name='tenderresult',
            name='ru_result_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='ru Results'),
        ),
    ]
