# Generated by Django 4.2.6 on 2024-04-17 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0007_rename_en_description_tender_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents_tender/')),
                ('description_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('description_kg', models.CharField(blank=True, max_length=255, null=True)),
                ('description_en', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_tender', to='tender.tender')),
            ],
        ),
    ]
