# Generated by Django 4.2.6 on 2024-04-18 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0008_documenttender'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentResultTender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents_result/')),
                ('description_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('description_kg', models.CharField(blank=True, max_length=255, null=True)),
                ('description_en', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_result', to='tender.tenderresult')),
            ],
        ),
    ]
