# Generated by Django 4.2.6 on 2024-04-17 17:09

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=160, null=True)),
                ('title_kg', models.CharField(blank=True, max_length=160, null=True)),
                ('title_en', models.CharField(blank=True, max_length=160, null=True)),
                ('target_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Ru Text')),
                ('target_kg', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='KG Text')),
                ('target_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='EN Text')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='NewsPhoto')),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
