# Generated by Django 4.2.6 on 2023-11-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galery',
            name='project',
        ),
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ManyToManyField(blank=True, to='news.galery'),
        ),
        migrations.AlterField(
            model_name='galery',
            name='photo',
            field=models.ImageField(upload_to='Galery'),
        ),
    ]
