# Generated by Django 4.2.6 on 2024-04-18 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(default=datetime.datetime(2024, 4, 18, 14, 15, 51, 982842, tzinfo=datetime.timezone.utc), max_length=160),
            preserve_default=False,
        ),
    ]
