# Generated by Django 4.2.6 on 2024-03-04 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='descrtiption',
        ),
    ]
