# Generated by Django 4.2.6 on 2024-03-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='photo',
        ),
    ]
