# Generated by Django 4.2.6 on 2024-03-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_descrtiption'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='descrtiption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
