# Generated by Django 4.2.6 on 2024-04-17 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_title_alter_news_title_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
    ]
