# Generated by Django 4.2.6 on 2024-03-04 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_descrtiption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='descrtiption',
            new_name='description',
        ),
    ]
