# Generated by Django 4.2.6 on 2024-03-13 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_descrtiption_news_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='photo',
        ),
        migrations.DeleteModel(
            name='NewsPhoto',
        ),
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ImageField(default=datetime.datetime(2024, 3, 13, 12, 24, 6, 41944, tzinfo=datetime.timezone.utc), upload_to='NewsPhoto'),
            preserve_default=False,
        ),
    ]
