# Generated by Django 4.2.6 on 2024-03-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph2',
            name='x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='graph2',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
