# Generated by Django 4.2.6 on 2024-04-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_alter_graph1_month_alter_graph2_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph1',
            name='month',
            field=models.CharField(choices=[('Январь', 'Январь'), ('fsd', 'fsd'), ('Март', 'Март'), ('Апрель', 'Апрель'), ('Май', 'Май'), ('Июнь', 'Июнь'), ('Июль', 'Июль'), ('Август', 'Август'), ('Сентябрь', 'Сентябрь'), ('Октябрь', 'Октябрь'), ('Ноябрь', 'Ноябрь'), ('Декабрь', 'Декабрь')], max_length=120),
        ),
    ]
