# Generated by Django 4.2.6 on 2024-04-04 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0006_alter_graph4_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph1',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
