# Generated by Django 4.2.6 on 2024-04-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0007_graph1_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph1',
            name='name',
        ),
        migrations.RemoveField(
            model_name='graph4',
            name='name',
        ),
        migrations.AddField(
            model_name='graph1',
            name='en_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='graph1',
            name='kg_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='graph1',
            name='ru_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='graph4',
            name='en_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='graph4',
            name='kg_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='graph4',
            name='ru_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
