# Generated by Django 4.2.6 on 2024-04-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0008_remove_graph1_name_remove_graph4_name_graph1_en_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graph1',
            old_name='en_name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='graph1',
            old_name='kg_name',
            new_name='name_kg',
        ),
        migrations.RenameField(
            model_name='graph1',
            old_name='ru_name',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='graph4',
            old_name='en_name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='graph4',
            old_name='kg_name',
            new_name='name_kg',
        ),
        migrations.RenameField(
            model_name='graph4',
            old_name='ru_name',
            new_name='name_ru',
        ),
    ]
