# Generated by Django 4.2.6 on 2024-04-18 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0009_rename_en_name_graph1_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph4',
            name='name_ru',
            field=models.CharField(default=datetime.datetime(2024, 4, 18, 14, 15, 27, 936135, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
