# Generated by Django 4.2.6 on 2023-11-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_rename_is_admin_admin_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
