# Generated by Django 4.2.6 on 2024-04-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(blank=True, max_length=256, null=True)),
                ('name_kg', models.CharField(blank=True, max_length=256, null=True)),
                ('name_en', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(choices=[('is_finished', 'is_finished'), ('in_progress', 'in_progress'), ('is_assigned', 'is_assigned')], max_length=100)),
                ('longitude', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=155)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('finished', models.IntegerField(blank=True, null=True)),
                ('depth', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
