# Generated by Django 4.2.6 on 2024-03-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('is_finished', 'is_finished'), ('in_progress', 'in_progress'), ('is_assigned', 'is_assigned')], max_length=100)),
                ('longitude', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=155)),
                ('location', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
    ]
