# Generated by Django 4.2.6 on 2024-04-18 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landslide_points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='name_ru',
            field=models.CharField(default=datetime.datetime(2024, 4, 18, 14, 15, 41, 836743, tzinfo=datetime.timezone.utc), max_length=256),
            preserve_default=False,
        ),
    ]
