# Generated by Django 4.2.6 on 2024-03-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landslide_points', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='color',
        ),
        migrations.AddField(
            model_name='point',
            name='depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='finished',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
