# Generated by Django 4.2.6 on 2024-04-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landslide_points', '0002_alter_point_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='name',
        ),
        migrations.AddField(
            model_name='point',
            name='en_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='kg_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='ru_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
