# Generated by Django 4.2.6 on 2024-04-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landslide_points', '0003_remove_point_name_point_en_name_point_kg_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='en_name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='kg_name',
            new_name='name_kg',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='ru_name',
            new_name='name_ru',
        ),
    ]
