# Generated by Django 4.2.6 on 2023-11-20 12:25

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=155)),
                ('photo', models.ImageField(upload_to='')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('is_finished', 'is_finished'), ('in_progress', 'in_progress'), ('is_assigned', 'is_assigned')], max_length=100)),
                ('longitude', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('owner', models.CharField(max_length=140)),
                ('budget', models.IntegerField()),
                ('deadline', models.DateField()),
                ('start_at', models.DateField(auto_now_add=True)),
                ('color', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.team')),
            ],
        ),
        migrations.CreateModel(
            name='MemberTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.team')),
            ],
        ),
    ]
