# Generated by Django 4.2.6 on 2023-11-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Photo')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ManyToManyField(blank=True, to='project.photo'),
        ),
    ]
