# Generated by Django 4.2.6 on 2024-04-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_caption_photo_en_caption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='en_description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='kg_description',
            new_name='description_kg',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='ru_description',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='en_caption',
            new_name='caption_en',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='kg_caption',
            new_name='caption_kg',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='ru_caption',
            new_name='caption_ru',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='en_description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='kg_description',
            new_name='description_kg',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ru_description',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='en_name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='kg_name',
            new_name='name_kg',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ru_name',
            new_name='name_ru',
        ),
    ]
